### ISSUE TITLE
Push images to Github Container Registry

### ISSUE THREAD

**Issue by duckfullstop** [squat/generic-device-plugin#5]
Docker Hub continues to do weird things to pull limits, license requirements, etc, so building and pushing containers to GHCR seems like a good idea.

I'm not 100% sure how we'd want to implement this - usually I just spin another workflow task with instructions to `docker push` to ghcr.io, but as we're making heavy use of Makefile (which isn't a native tongue by any stretch) I figured this is better as an issue rather than a draft PR.

**Comment by squat** [comment]
Ack, agreed. I'd like to move more things off of docker hub! I think we can relatively easily push the images to both registries in the workflow. I'll take a look. I think (without modifying the CI workflow too much) it's a matter of adding a second block to login to the GitHub registry and then adding a second invocation of `make manifest` under the first but this time with `REGISTRY=ghcr.io make manifest`

**Comment by squat** [comment]
We now push to push GitHub Container Registry as well as Docker Hub!
