### ISSUE TITLE
Execution failed: failed to parse device

### ISSUE THREAD

**Issue by pmandrik** [squat/generic-device-plugin#50]
Dear developers, 

following device flag value taken from https://github.com/squat/generic-device-plugin/#overview is failing at my 22.04.1 ubuntu system:
```
./bin/amd64/generic-device-plugin --device {"name": "video", "groups": [{"paths": [{"path": "/dev/video0"}]}]}
Execution failed: failed to parse device "{name:": error converting YAML to JSON: yaml: line 1: did not find expected node content
```
while version with following single quotes works fine:
`
./bin/amd64/generic-device-plugin --device '{"name": "video", "groups": [{"paths": [{"path": "/dev/video0"}]}]}'
`
please fix if relevant,

Best regards, P.~Mandrik

**Comment by squat** [comment]
Indeed this does need single quotes! I'm happy to accept a PR fixing it :)
