### ISSUE TITLE
Generic Device Plugin vs KubeEdge

### ISSUE THREAD

**Issue by zbm-armada** [squat/generic-device-plugin#57]
Hi I'm looking to use a bluetooth usb dongle with my kubernetes cluster to connect with another bluetooth-enabled sensor. 

I'm trying to understand the difference between this Generic Device Plugin and the device implementation in [KubeEdge](https://kubeedge.io/docs/developer/device_crd). 

I'm curious how you all differentiate between the two. What are the tradeoffs between the this system and KubeEdge, is there one that is more secure/robust?

Thanks in advance.

**Comment by zbm-armada** [comment]
Really appreciate you taking the time to respond, thank you. 

I hear what you are saying about distinct and potentially complimentary. Sounds like generic-device-plugin has a [similar approach to k3s](https://training.linuxfoundation.org/blog/opportunities-and-challenges-in-edge-computing-under-kubernetes/), "_Things can get tricky when the edge device is separate from the node, such as a remote sensor device that communicates to an edge node via Bluetooth; the K3S architecture will have a hard time handling this situation out of the box. On the other hand, KubeEdge is designed to work with edge nodes that do not have sensors, cameras and other types of edge devices attached directly to the motherboard_." <-- This was the article that sparked my curiosity and lead me to finding generic-device-plugin

I guess it comes down to controlling the bluetooth connections entirely in the pod (generic-device-plugin), or defining the parameters for connection and letting KubeEdge handle the connections. The number of physically attached devices could help guide that decision - lots of bluetooth devices, go with KubeEdge. Physical dongle with just one bluetooth sensor connected? Go with generic-device-plugin. 

Anyway I'm just trying to sort out my thoughts and understand the IoT Kubernetes landscape. Thanks again for your input!

**Comment by squat** [comment]
I think your overall analysis is spot on! I'll close this issue for now since it seems you know what direction to take. Please reopen if you need any more input.
